name: Check codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint with markdownlint
        run: yarn lint:markdownlint

      - name: Lint with prettier
        run: yarn lint:prettier

      - name: Lint with tsc
        run: yarn lint:tsc

      - name: Lint with tslint
        run: yarn lint:tslint

      - name: Lint with yarn-deduplicate
        run: yarn lint:yarn-deduplicate

  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [12, 14, 16]
        include:
          - os: ubuntu-latest
            node: 14
            coverage: 1
        exclude:
          - os: macos-latest
            node: 12
          - os: windows-latest
            node: 12
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test
        env:
          REPORT_TEST_RESULTS_AND_COVERAGE: ${{ matrix.coverage }}

      - name: Report code coverage to codecov.io
        uses: codecov/codecov-action@v1
        if: matrix.coverage == 1
        with:
          file: ./coverage/cobertura-coverage.xml
