name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run build
        run: yarn build

  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint with eslint
        if: ${{ success() || failure() }}
        run: yarn lint:eslint

      - name: Lint with markdownlint
        if: ${{ success() || failure() }}
        run: yarn lint:markdownlint

      - name: Lint with prettier
        if: ${{ success() || failure() }}
        run: yarn lint:prettier

      - name: Lint with tsc
        if: ${{ success() || failure() }}
        run: yarn lint:tsc

      - name: Lint with yarn-dedupe
        if: ${{ success() || failure() }}
        run: yarn lint:yarn-dedupe

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
        node: [14, 16, 18, 19]
        include:
          - os: ubuntu-22.04
            node: 18
            extra: coverage
        exclude:
          - os: ubuntu-22.04
            node: 18
          - os: macos-12
            node: 19
          - os: windows-2022
            node: 19

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: "Prettier v2: Run tests"
        if: ${{ success() || failure() }}
        run: yarn test
        env:
          TEST_COVERAGE: ${{ matrix.extra == 'coverage' }}

      - name: "Prettier v2: Report code coverage to codecov.io"
        uses: codecov/codecov-action@v3
        if: matrix.extra == 'coverage'
        with:
          files: coverage/lcov.info
          label: prettier-v2

      - name: "Prettier v3: Run tests"
        if: ${{ success() || failure() }}
        run: yarn test
        env:
          TEST_COVERAGE: ${{ matrix.extra == 'coverage' }}
          PRETTIER_V3: "true"

      - name: "Prettier v3: Report code coverage to codecov.io"
        uses: codecov/codecov-action@v3
        if: matrix.extra == 'coverage'
        with:
          files: coverage/lcov.info
          label: prettier-v3
