name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint with eslint
        run: yarn lint:eslint

      - name: Lint with markdownlint
        run: yarn lint:markdownlint

      - name: Lint with prettier
        run: yarn lint:prettier

      - name: Lint with tsc
        run: yarn lint:tsc

      - name: Lint with yarn-deduplicate
        run: yarn lint:yarn-deduplicate

  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
        node: [14, 16, 18, 19]
        exclude:
          - os: macos-12
            node: 14
          - os: macos-12
            node: 19
          - os: ubuntu-22.04
            node: 18
          - os: windows-2022
            node: 14
          - os: windows-2022
            node: 19
        include:
          - os: ubuntu-22.04
            node: 18
            coverage: 1

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test
        env:
          REPORT_TEST_RESULTS_AND_COVERAGE: ${{ matrix.coverage }}

      - name: Report code coverage to codecov.io
        uses: codecov/codecov-action@v3
        if: matrix.coverage == 1
        with:
          files: ./coverage/cobertura-coverage.xml
