name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run build
        run: yarn build

  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint with eslint
        if: ${{ success() || failure() }}
        run: yarn lint:eslint

      - name: Lint with markdownlint
        if: ${{ success() || failure() }}
        run: yarn lint:markdownlint

      - name: Lint with prettier
        if: ${{ success() || failure() }}
        run: yarn lint:prettier

      - name: Lint with tsc
        if: ${{ success() || failure() }}
        run: yarn lint:tsc

      - name: Lint with yarn-dedupe
        if: ${{ success() || failure() }}
        run: yarn lint:yarn-dedupe

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, windows-2022, ubuntu-22.04]
        node: [14, 16, 18]
        exclude:
          - os: ubuntu-22.04
            node: 18
        include:
          - os: ubuntu-22.04
            node: 18
            extra: coverage
          - os: ubuntu-22.04
            node: 19

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: "Prettier v1: Run tests"
        if: ${{ success() || failure() }}
        run: yarn test
        env:
          COVERAGE: ${{ matrix.extra == 'coverage' }}
          PRETTIER_VERSION: "1"

      - name: "Prettier v1: Report coverage to codecov.io"
        uses: codecov/codecov-action@v3
        if: matrix.extra == 'coverage'
        with:
          files: coverage/lcov.info
          label: prettier-v1

      - name: "Prettier v2: Run tests"
        if: ${{ success() || failure() }}
        run: yarn test
        env:
          COVERAGE: ${{ matrix.extra == 'coverage' }}

      - name: "Prettier v2: Report coverage to codecov.io"
        uses: codecov/codecov-action@v3
        if: matrix.extra == 'coverage'
        with:
          files: coverage/lcov.info
          label: prettier-v2

      - name: "Prettier v3: Run tests"
        if: ${{ success() || failure() }}
        ## Running both tests on Node 14 causes exit code 129/1 on Ubuntu/Windows
        ## TODO: Remove after dropping Node 14 support
        run: ${{ matrix.node == 14 && 'yarn test cache && yarn test main' || 'yarn test' }}
        env:
          COVERAGE: ${{ matrix.extra == 'coverage' }}
          PRETTIER_VERSION: "3"

      - name: "Prettier v3: Report coverage to codecov.io"
        uses: codecov/codecov-action@v3
        if: matrix.extra == 'coverage'
        with:
          files: coverage/lcov.info
          label: prettier-v3
