trigger:
  - master

jobs:
  - job: Lint
    displayName: Lint
    pool:
      vmImage: "Ubuntu 16.04"
    strategy:
      matrix:
        (Node 10):
          NODE_VERSION: 10
    steps:
      - template: jobs/lint.yml

  - job: Test_Linux
    displayName: Test on Linux
    pool:
      vmImage: "Ubuntu 16.04"
    strategy:
      matrix:
        (Node 6):
          NODE_VERSION: 6
        (Node 8):
          NODE_VERSION: 8
        (Node 10 + test results & coverage):
          NODE_VERSION: 10
          REPORT_TEST_RESULTS_AND_COVERAGE: true
        (Node 11):
          NODE_VERSION: 11
    steps:
      - template: jobs/test.yml

  - job: Test_macOS
    displayName: Test on macOS
    pool:
      vmImage: macos-10.13
    strategy:
      matrix:
        (Node 10):
          NODE_VERSION: 10
    steps:
      - template: jobs/test.yml

  - job: Test_Windows
    displayName: Test on Windows
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        (Node 10):
          NODE_VERSION: 10
    steps:
      - template: jobs/test.yml
